"""Deploy a client adapter on the local DGX Spark via vLLM.

Launches vLLM with --enable-lora, writes a systemd service unit, returns
the internal endpoint URL. Client endpoints are distinguished by API key
(not by port — we run all clients on one vLLM process for memory efficiency,
using the shared-base + LoRA hot-swap architecture).

For the first implementation, this just writes a launch script the operator
runs manually. Per-client multi-LoRA routing is a follow-up to build once
there are 2+ concurrent clients.
"""
from __future__ import annotations

import json
import logging
import shutil
import subprocess
import time
from pathlib import Path

log = logging.getLogger(__name__)

SPARK_VLLM_PORT = 8010           # Pylox pipeline vLLM — distinct from trtllm-eagle3 on 8002
SPARK_RUN_DIR = Path("/home/fenexpertai/fine-tune-pipeline/deploy/runs")


def _build_vllm_command(base_model: str, adapters: list[tuple[str, Path]], cfg: dict) -> list[str]:
    """Build the vllm serve command with multi-LoRA mounts."""
    args = ["vllm", "serve", base_model, "--port", str(SPARK_VLLM_PORT)]
    args.extend(cfg["deploy"]["spark"]["vllm_args"])

    if adapters:
        lora_mounts = [f"{name}={str(path.resolve())}" for name, path in adapters]
        args.extend(["--lora-modules", *lora_mounts])

    return args


def deploy_client_endpoint(
    client_slug: str,
    adapter_path: Path,
    cfg: dict,
) -> str:
    """Write launch script + return internal endpoint URL.

    Per-client API key routing is handled separately by a Cloudflare worker
    or nginx reverse proxy (see ops/provision_endpoint.py).
    """
    SPARK_RUN_DIR.mkdir(parents=True, exist_ok=True)

    # Collect all deployed client adapters (so restart keeps them all mounted)
    state_path = SPARK_RUN_DIR / "deployed_adapters.json"
    if state_path.exists():
        deployed = json.loads(state_path.read_text())
    else:
        deployed = {}
    deployed[client_slug] = str(adapter_path.resolve())
    state_path.write_text(json.dumps(deployed, indent=2))

    adapters = [(name, Path(path)) for name, path in deployed.items()]
    cmd = _build_vllm_command(cfg["base_model"], adapters, cfg)

    launch_script = SPARK_RUN_DIR / "launch.sh"
    launch_script.write_text(f"""#!/bin/bash
# Auto-generated by Pylox Systems fine-tune pipeline
# Serves {len(adapters)} client adapters on a shared base model.
# Restart when adding/removing clients.

set -e

# Ensure gpt-oss-120b is stopped so vLLM has memory
docker stop trtllm-eagle3 2>/dev/null || true
sleep 5

exec {' '.join(shlex_quote(x) for x in cmd)}
""")
    launch_script.chmod(0o755)

    endpoint = f"http://localhost:{SPARK_VLLM_PORT}/v1"
    log.info(f"Spark deploy prepared. Run: {launch_script}")
    log.info(f"Endpoint will be: {endpoint}")
    log.info(f"Client API identifier: lora_module='{client_slug}' in requests")

    return endpoint


def stop_client_endpoint(client_slug: str) -> None:
    """Remove a client's adapter from the deployed set. Requires vLLM restart to take effect."""
    state_path = SPARK_RUN_DIR / "deployed_adapters.json"
    if not state_path.exists():
        log.info("No deployed adapters")
        return
    deployed = json.loads(state_path.read_text())
    if client_slug in deployed:
        del deployed[client_slug]
        state_path.write_text(json.dumps(deployed, indent=2))
        log.info(f"Removed {client_slug}. Restart vLLM to apply (run {SPARK_RUN_DIR / 'launch.sh'}).")


def shlex_quote(s: str) -> str:
    """shlex.quote shim that handles None."""
    import shlex
    return shlex.quote(str(s))


if __name__ == "__main__":
    import argparse
    import yaml

    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(message)s")
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("client", type=str)
    parser.add_argument("adapter", type=Path)
    parser.add_argument("config", type=Path)
    args = parser.parse_args()

    cfg = yaml.safe_load(args.config.read_text())
    print(deploy_client_endpoint(args.client, args.adapter, cfg))
